spring:
  application:
    name: couponMerchants
  datasource:
    url: jdbc:mysql://localhost:3306/passbook?autoReconnect=true
    username: root
    password: password
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: passbook
    listener:
      concurrency: 4

server:
  port: 9527

logging:
  level: debug
  file: coupon-merchants.log